server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://_________:3306/instagram # RDS 인스턴스 엔드포인트
    username: ______ # (RDS 인스턴스 생성 시 셋팅한) RDS 마스터 사용자 이름
    password: ______ # (RDS 인스턴스 생성 시 셋팅한) RDS 마스터 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  cloud:
    aws:
      credentials:
        access-key: _________ # IAM 통해서 발급받은 액세스 키
        secret-key: _________ # IAM 통해서 발급받은 비밀 액세스 키
      s3:
        bucket: _______ # 생성한 버킷명
      region:
        static: ap-northeast-2