server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://___________:3306/instagram
    username: ______
    password: ______
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true